version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: scraping-master-mailhog
      ports:
        - "8889:8025"

    postgres:
      image: postgres:12-alpine
      container_name: scraping-master-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=scraping-master
      ports:
        - "8892:5432"

    postgres-testing:
      image: postgres:12-alpine
      container_name: scraping-master-postgres-test
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=scraping-master-test
      ports:
        - "8893:5432"

    webserver:
      image: nginx:alpine
      container_name: scraping-master-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9999:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: scraping-master-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      environment:
        - PHP_IDE_CONFIG=serverName=docker-server

    redis:
      image: redis:alpine
      container_name: scraping-master-redis
      ports:
        - "6379:6379"
